In [45]:
import numpy as np
from numpy import linalg as LA 
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA, FastICA,KernelPCA,TruncatedSVD

In [46]:
XMat=np.array([(3,2,1),(2,4,5),(1,2,3),(0,2,5)])
average= np.mean(XMat,axis=0) #Find the sample mean.
average

array([ 1.5,  2.5,  3.5])

In [47]:
m, n = np.shape(XMat)
data_adjust = []
avgs = np.tile(average, (m, 1))
data_adjust = XMat - avgs
covX = np.cov(data_adjust.T)   #Find the sample covariance matrix Q.
covX

array([[ 1.66666667,  0.33333333, -1.66666667],
       [ 0.33333333,  1.        ,  1.        ],
       [-1.66666667,  1.        ,  3.66666667]])

In [48]:
#Find the eigenvalues and eigenvectors.
featValue, featVec=  np.linalg.eig(covX)  
featValue, featVec

(array([ 4.74888619,  1.56450706,  0.01994008]),
 array([[-0.45056922, -0.66677184, -0.59363515],
        [ 0.19247228, -0.72187235,  0.66472154],
        [ 0.87174641, -0.18524476, -0.45358856]]))

In [49]:
#Reconstruct the original samples from the PCA coefficients.
#Approximate the samples using principle components corresponding to the two largest eigenvalues.
index = np.argsort(-featValue)
finalData = []
selectVec = np.matrix(featVec.T[index[:2]])
finalData = data_adjust * selectVec.T 
reconData = (finalData * selectVec) + average  
finalData,reconData

(matrix([[-2.95145599, -0.17610969],
         [ 1.37104342, -1.69406159],
         [-0.30682473,  0.78694448],
         [ 1.8872373 ,  1.0832268 ]]),
 matrix([[ 2.94726021,  2.05905526,  0.95970224],
         [ 2.0118026 ,  3.98678407,  5.0090182 ],
         [ 1.11353336,  1.87287129,  3.0867493 ],
         [-0.07259617,  2.08128939,  4.94453025]]))

In [50]:
U,S,V = np.linalg.svd(XMat, full_matrices=False)
lam = S**2
PoV = np.cumsum(lam)/np.sum(lam)
PoV

array([ 0.89793936,  0.99755596,  1.        ])